# Generated by Django 2.2 on 2022-06-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36, verbose_name='Заголовок')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('publisher_at', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'резюме',
                'verbose_name_plural': 'резюме',
                'db_table': 'resume',
                'permissions': (('can_publish', 'Можно опубликовать'),),
            },
        ),
        migrations.AlterModelTable(
            name='vacancy',
            table='vacancy',
        ),
    ]
