# Generated by Django 2.2 on 2022-06-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_employment', '0002_auto_20220615_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'permissions': (('can_publish', 'Можно опубликовать'), ('can_change', 'Можно изменять'), ('can_add', 'Можно добавить'), ('can_view', 'Можно просматривать')), 'verbose_name': 'резюме', 'verbose_name_plural': 'резюме'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'permissions': (('can_publish', 'Можно опубликовать'), ('can_change', 'Можно изменять'), ('can_add', 'Можно добавить'), ('can_view', 'Можно просматривать')), 'verbose_name': 'вакансия', 'verbose_name_plural': 'вакансии'},
        ),
    ]
