# Generated by Django 2.2 on 2022-04-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(db_index=True, max_length=130, verbose_name='Рубрика')),
            ],
            options={
                'db_table': 'heading',
            },
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ФИО')),
                ('mail_address', models.EmailField(max_length=100, verbose_name='Email адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок')),
                ('descriptions', models.CharField(max_length=1500, verbose_name='Описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('create_start_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('create_end_at', models.DateTimeField(auto_now=True, verbose_name='Дата окончания публикации')),
                ('view_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('heading_status', models.ForeignKey(default=True, null=None, on_delete=django.db.models.deletion.CASCADE, to='advertisements.Heading', verbose_name='Рубрика')),
                ('users_status', models.ForeignKey(default=True, null=None, on_delete=django.db.models.deletion.CASCADE, to='advertisements.UsersInfo', verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'advertisements',
            },
        ),
    ]
