# Generated by Django 2.2 on 2022-05-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20220502_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='type_adv',
            field=models.CharField(default='Free', max_length=25, verbose_name='Тип объявления'),
        ),
    ]
