# Generated by Django 2.2 on 2022-05-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_type_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='heading_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements.Heading', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='users_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements.UsersInfo', verbose_name='Пользователь'),
        ),
    ]
