# Generated by Django 2.2 on 2022-06-13 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('comments', models.CharField(max_length=300, verbose_name='Комментарий')),
                ('news', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_news', to='app_news.News', verbose_name='Новость')),
                ('users', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
