# Generated by Django 2.2 on 2022-04-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_auto_20220424_1343'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
