# Generated by Django 2.2 on 2022-04-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_auto_20220424_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
