# Generated by Django 2.2 on 2022-04-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_auto_20220425_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
    ]
