# Generated by Django 2.2 on 2022-04-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0010_auto_20220425_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок'),
        ),
    ]
