# Generated by Django 2.2 on 2022-06-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
