# Generated by Django 2.2 on 2022-06-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20220614_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discount',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
