# Generated by Django 2.2 on 2022-04-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='view_count',
            field=models.FloatField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
