# Generated by Django 2.2 on 2022-05-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fastfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='mail_address',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waiter',
            name='phone',
            field=models.CharField(default=1, max_length=15, verbose_name='№ телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=60, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=35, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='first_name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='last_name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='second_name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Отчество'),
        ),
    ]
