# Generated by Django 2.2 on 2022-05-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fastfood', '0002_auto_20220522_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='status_employ',
            field=models.CharField(choices=[('a', 'Принят'), ('f', 'Уволен'), ('s', 'Больничный'), ('h', 'Отпуск')], default='a', max_length=1),
        ),
    ]
