# Generated by Django 2.2 on 2022-05-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fastfood', '0003_waiter_status_employ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='status_employ',
            field=models.CharField(choices=[('a', 'accept'), ('f', 'fire'), ('s', 'sick_list'), ('h', 'holiday')], default='f', max_length=1),
        ),
    ]
