# Generated by Django 2.2 on 2022-05-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fastfood', '0005_auto_20220523_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='status_employ',
            field=models.CharField(choices=[('т', 'Трудоустроен'), ('у', 'Уволен'), ('б', 'Больничный'), ('о', 'Отпуск')], default='т', max_length=1),
        ),
    ]
