# Generated by Django 2.2 on 2022-06-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('descriptions', models.CharField(max_length=500, verbose_name='Описание')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата редактирования')),
                ('activated', models.BooleanField(default=False, verbose_name='Активность')),
                ('status', models.CharField(choices=[('a', 'Активно'), ('n', 'Неактивно')], default='n', max_length=1, verbose_name='Статус')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['created_at'],
            },
        ),
    ]
