# Generated by Django 2.2 on 2022-05-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='Статья')),
                ('article', models.CharField(max_length=2000, verbose_name='Содержание')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('refactor_date', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('flag_news', models.BooleanField(default=False, verbose_name='Активность')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=35, verbose_name='Имя пользователя')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('news', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_name', to='app_news.News')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
