# Generated by Django 2.2 on 2022-05-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaries',
            name='news_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='app_news.News', verbose_name='Новость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='comment_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newses', to='app_news.Commentaries', verbose_name='Комментарий'),
        ),
    ]
