# Generated by Django 2.2 on 2022-05-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20220507_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comment_status',
        ),
    ]
