# Generated by Django 2.2 on 2022-05-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_remove_news_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaries',
            name='news_status',
        ),
        migrations.AlterField(
            model_name='commentaries',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='app_news.News', verbose_name='Новость'),
        ),
    ]
