# Generated by Django 2.2 on 2022-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_auto_20220507_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaries',
            name='news',
        ),
        migrations.AddField(
            model_name='commentaries',
            name='news',
            field=models.ManyToManyField(related_name='commentaries', to='app_news.News', verbose_name='Новость'),
        ),
    ]
