# Generated by Django 2.2 on 2022-05-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_auto_20220507_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaries',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_news.Commentaries'),
            preserve_default=False,
        ),
    ]
