# Generated by Django 2.2 on 2022-05-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0010_auto_20220513_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaries',
            name='news',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaries_news', to='app_news.News', verbose_name='Новость'),
        ),
    ]
